# Site/SEO settings
email: hello@tlf20.com
baseurl: "www.tlf20.com"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: TLF 20
title: The 59 awesome fellows
description: >
  A group of 59 awesome tech leaders trying to contribute towards a better future.
url: http://www.tlf20.com
twitter_username: tlf20
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/tlf20
  - name: instagram
    url: https://www.instagram.com/tlf20/
  - name: linkedin
    url: https://www.linkedin.com/in/tlf20/
  - name: github
    url: https://github.com/tlf2020
  - name: codepen
    url: https://codepen.io/tlf20/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ravinder
    bio: Check Web Site
    url: http://www.ravinderpayal.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
